### ISSUE TITLE
Нету лицензии на код

### ISSUE THREAD

**Issue by 4144** [izvolov/burst#70]
Хотел использовать некоторые из ваших файлов в опесоурс проекте,
но т.к. нет лицензии, это означает что ваш код ни кто и не где не имеет право использовать...

Можете добавить какую-либо GPL совместимую лицензию?

**Comment by izvolov** [comment]
Могли бы вы дать ссылку, где можно подробно про это почитать? Я всегда считал, что если не указано обратное, то код можно использовать где и как угодно.

**Comment by 4144** [comment]
Не помню где я это взял, возможно еще зависит от страны.
Если вам все равно кто и как будет использовать ваш код, то возможно стоит выбрать лицензию public domain или CC0. Это почти одно и тоже, но вторая признается много где.

**Comment by izvolov** [comment]
Поставил BSL.
