### ISSUE TITLE
А почему на русском? 

### ISSUE THREAD

**Issue by bagobor** [izvolov/burst#95]
Привет, 

Отличная работа!
Это немеренно что материал на русском или нужна помощь с переводом?

**Comment by izvolov** [comment]
Привет.

Спасибо на добром слове.

Перевод планируется, и даже уже частично начался (https://github.com/izvolov/burst/blob/master/include/burst/algorithm/radix_sort.hpp#L55), но работа эта большая и неблагодарная.

Если есть желание и возможность, то с удовольствием приму помощь с переводом.

**Comment by bagobor** [comment]
@izvolov буду рад помочь. ставь задачки буду делать по мере времени.

**Comment by izvolov** [comment]
@bagobor, круто.

Тогда предлагаю начать с главного — с readme. Постараюсь в ближайшее время привести его в наиболее актуальный вид, и начнём.

> очень рекомендую https://www.grammarly.com/

Сервис, кстати, полезный, буду иметь в виду.

**Comment by bagobor** [comment]
я начал им пользоваться года 2 назад. мне нравится ... 
ок. жду тикеты тогда )

по коду кстати помощь не нужна ? )

**Comment by izvolov** [comment]
> по коду кстати помощь не нужна ? )

Идей масса :) . Если у тебя есть телеграм, предлагаю списаться там. Можешь меня найти по имени: dmitriyizvolov . Или предложи другой удобный способ связи.
